import type { Metadata } from "next";
import "@/styles/globals.css";
import { Web3Provider } from "@/components/web3-privoder";
import { I18nProviderClient } from "@/locales/client";

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default async function RootLayout({
  params,
  children,
}: Readonly<{
  params: Promise<{ locale: string }>;
  children: React.ReactNode;
}>) {
  const { locale } = await params;
  return (
    <html lang={locale}>
      <body>
        <Web3Provider>
          <I18nProviderClient locale={locale}>
            {children}
          </I18nProviderClient>
        </Web3Provider>
      </body>
    </html>
  );
}
